"""
    Country code to Accept-Language header mapping.
    Country codes in format ISO 3166-1 alpha-2.
    Source: https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes
    Language codes in format IETF BCP 47.
    Source: https://en.wikipedia.org/wiki/IETF_language_tag
"""


CC_ACCEPT_LANGUAGE_MAP = {
    "AF": "ps-AF",      # Pashto (Afghanistan)
    "AL": "sq-AL",      # Albanian (Albania)
    "DZ": "ar-DZ",      # Arabic (Algeria)
    "AD": "ca-AD",      # Catalan (Andorra)
    "AO": "pt-AO",      # Portuguese (Angola)
    "AI": "en-AI",      # English (Anguilla)
    "AQ": "en-AQ",      # English (Antarctica)
    "AG": "en-AG",      # English (Antigua and Barbuda)
    "AR": "es-AR",      # Spanish (Argentina)
    "AM": "hy-AM",      # Armenian (Armenia)
    "AW": "nl-AW",      # Dutch (Aruba)
    "AU": "en-AU",      # English (Australia)
    "AT": "de-AT",      # German (Austria)
    "AZ": "az-AZ",      # Azerbaijani (Azerbaijan)
    "BS": "en-BS",      # English (Bahamas)
    "BH": "ar-BH",      # Arabic (Bahrain)
    "BD": "bn-BD",      # Bengali (Bangladesh)
    "BB": "en-BB",      # English (Barbados)
    "BY": "be-BY",      # Belarusian (Belarus)
    "BE": "nl-BE",      # Dutch (Belgium)
    "BZ": "en-BZ",      # English (Belize)
    "BJ": "fr-BJ",      # French (Benin)
    "BM": "en-BM",      # English (Bermuda)
    "BT": "dz-BT",      # Dzongkha (Bhutan)
    "BO": "es-BO",      # Spanish (Bolivia)
    "BA": "bs-BA",      # Bosnian (Bosnia and Herzegovina)
    "BW": "en-BW",      # English (Botswana)
    "BR": "pt-BR",      # Portuguese (Brazil)
    "BN": "ms-BN",      # Malay (Brunei)
    "BG": "bg-BG",      # Bulgarian (Bulgaria)
    "BF": "fr-BF",      # French (Burkina Faso)
    "BI": "fr-BI",      # French (Burundi)
    "BV": "no-BV",      # Norwegian (Bouvet Island)
    "KH": "km-KH",      # Khmer (Cambodia)
    "CM": "fr-CM",      # French (Cameroon)
    "CA": "en-CA",      # English (Canada)
    "CV": "pt-CV",      # Portuguese (Cape Verde)
    "KY": "en-KY",      # English (Cayman Islands)
    "CF": "fr-CF",      # French (Central African Republic)
    "TD": "fr-TD",      # French (Chad)
    "CL": "es-CL",      # Spanish (Chile)
    "CN": "zh-CN",      # Chinese (China)
    "CX": "en-CX",      # English (Christmas Island)
    "CC": "en-CC",      # English (Cocos Islands)
    "CO": "es-CO",      # Spanish (Colombia)
    "KM": "fr-KM",      # French (Comoros)
    "CG": "fr-CG",      # French (Congo)
    "CD": "fr-CD",      # French (Democratic Republic of Congo)
    "CK": "en-CK",      # English (Cook Islands)
    "CR": "es-CR",      # Spanish (Costa Rica)
    "CI": "fr-CI",      # French (Côte d'Ivoire)
    "HR": "hr-HR",      # Croatian (Croatia)
    "CU": "es-CU",      # Spanish (Cuba)
    "CY": "el-CY",      # Greek (Cyprus)
    "CZ": "cs-CZ",      # Czech (Czechia)
    "DK": "da-DK",      # Danish (Denmark)
    "DJ": "fr-DJ",      # French (Djibouti)
    "DM": "en-DM",      # English (Dominica)
    "DO": "es-DO",      # Spanish (Dominican Republic)
    "EC": "es-EC",      # Spanish (Ecuador)
    "EG": "ar-EG",      # Arabic (Egypt)
    "SV": "es-SV",      # Spanish (El Salvador)
    "AE": "ar-AE",      # Arabic (United Arab Emirates)
    "ER": "ti-ER",      # Tigrinya (Eritrea)
    "EE": "et-EE",      # Estonian (Estonia)
    "ET": "am-ET",      # Amharic (Ethiopia)
    "FK": "en-FK",      # English (Falkland Islands)
    "FO": "fo-FO",      # Faroese (Faroe Islands)
    "FJ": "en-FJ",      # English (Fiji)
    "FI": "fi-FI",      # Finnish (Finland)
    "FR": "fr-FR",      # French (France)
    "GF": "fr-GF",      # French (French Guiana)
    "PF": "fr-PF",      # French (French Polynesia)
    "TF": "fr-TF",      # French (French Southern Territories)
    "GA": "fr-GA",      # French (Gabon)
    "GM": "en-GM",      # English (Gambia)
    "GE": "ka-GE",      # Georgian (Georgia)
    "DE": "de-DE",      # German (Germany)
    "GH": "en-GH",      # English (Ghana)
    "GI": "en-GI",      # English (Gibraltar)
    "GR": "el-GR",      # Greek (Greece)
    "GL": "kl-GL",      # Kalaallisut (Greenland)
    "GD": "en-GD",      # English (Grenada)
    "GP": "fr-GP",      # French (Guadeloupe)
    "GU": "en-GU",      # English (Guam)
    "GT": "es-GT",      # Spanish (Guatemala)
    "GG": "en-GG",      # English (Guernsey)
    "GN": "fr-GN",      # French (Guinea)
    "GW": "pt-GW",      # Portuguese (Guinea-Bissau)
    "GY": "en-GY",      # English (Guyana)
    "HT": "fr-HT",      # French (Haiti)
    "HK": "zh-HK",      # Chinese (Hong Kong)
    "HU": "hu-HU",      # Hungarian (Hungary)
    "IS": "is-IS",      # Icelandic (Iceland)
    "IN": "hi-IN",      # Hindi (India)
    "ID": "id-ID",      # Indonesian (Indonesia)
    "IR": "fa-IR",      # Persian (Iran)
    "IQ": "ar-IQ",      # Arabic (Iraq)
    "IE": "en-IE",      # English (Ireland)
    "IM": "en-IM",      # English (Isle of Man)
    "IL": "he-IL",      # Hebrew (Israel)
    "IT": "it-IT",      # Italian (Italy)
    "JM": "en-JM",      # English (Jamaica)
    "JP": "ja-JP",      # Japanese (Japan)
    "JE": "en-JE",      # English (Jersey)
    "JO": "ar-JO",      # Arabic (Jordan)
    "KZ": "kk-KZ",      # Kazakh (Kazakhstan)
    "KE": "en-KE",      # English (Kenya)
    "KI": "en-KI",      # English (Kiribati)
    "KP": "ko-KP",      # Korean (North Korea)
    "KR": "ko-KR",      # Korean (South Korea)
    "KW": "ar-KW",      # Arabic (Kuwait)
    "KG": "ky-KG",      # Kyrgyz (Kyrgyzstan)
    "LA": "lo-LA",      # Lao (Laos)
    "LV": "lv-LV",      # Latvian (Latvia)
    "LB": "ar-LB",      # Arabic (Lebanon)
    "LS": "en-LS",      # English (Lesotho)
    "LR": "en-LR",      # English (Liberia)
    "LY": "ar-LY",      # Arabic (Libya)
    "LI": "de-LI",      # German (Liechtenstein)
    "LT": "lt-LT",      # Lithuanian (Lithuania)
    "LU": "lb-LU",      # Luxembourgish (Luxembourg)
    "MO": "zh-MO",      # Chinese (Macao)
    "MK": "mk-MK",      # Macedonian (Macedonia)
    "MG": "mg-MG",      # Malagasy (Madagascar)
    "MW": "en-MW",      # English (Malawi)
    "MY": "ms-MY",      # Malay (Malaysia)
    "MV": "dv-MV",      # Dhivehi (Maldives)
    "ML": "fr-ML",      # French (Mali)
    "MT": "mt-MT",      # Maltese (Malta)
    "MH": "en-MH",      # English (Marshall Islands)
    "MQ": "fr-MQ",      # French (Martinique)
    "MR": "ar-MR",      # Arabic (Mauritania)
    "MU": "en-MU",      # English (Mauritius)
    "YT": "fr-YT",      # French (Mayotte)
    "MX": "es-MX",      # Spanish (Mexico)
    "FM": "en-FM",      # English (Micronesia)
    "MD": "ro-MD",      # Romanian (Moldova)
    "MC": "fr-MC",      # French (Monaco)
    "MN": "mn-MN",      # Mongolian (Mongolia)
    "ME": "sr-ME",      # Serbian (Montenegro)
    "MA": "ar-MA",      # Arabic (Morocco)
    "MZ": "pt-MZ",      # Portuguese (Mozambique)
    "MM": "my-MM",      # Burmese (Myanmar)
    "NA": "en-NA",      # English (Namibia)
    "NR": "en-NR",      # English (Nauru)
    "NP": "ne-NP",      # Nepali (Nepal)
    "NL": "nl-NL",      # Dutch (Netherlands)
    "AN": "nl-AN",      # Dutch (Netherlands Antilles)
    "NC": "fr-NC",      # French (New Caledonia)
    "NZ": "en-NZ",      # English (New Zealand)
    "NI": "es-NI",      # Spanish (Nicaragua)
    "NE": "fr-NE",      # French (Niger)
    "NG": "en-NG",      # English (Nigeria)
    "NU": "en-NU",      # English (Niue)
    "NF": "en-NF",      # English (Norfolk Island)
    "MP": "en-MP",      # English (Northern Mariana Islands)
    "NO": "no-NO",      # Norwegian (Norway)
    "OM": "ar-OM",      # Arabic (Oman)
    "PK": "ur-PK",      # Urdu (Pakistan)
    "PW": "en-PW",      # English (Palau)
    "PS": "ar-PS",      # Arabic (Palestine)
    "PA": "es-PA",      # Spanish (Panama)
    "PG": "en-PG",      # English (Papua New Guinea)
    "PY": "es-PY",      # Spanish (Paraguay)
    "PE": "es-PE",      # Spanish (Peru)
    "PH": "en-PH",      # English (Philippines)
    "PN": "en-PN",      # English (Pitcairn Islands)
    "PL": "pl-PL",      # Polish (Poland)
    "PT": "pt-PT",      # Portuguese (Portugal)
    "PR": "es-PR",      # Spanish (Puerto Rico)
    "QA": "ar-QA",      # Arabic (Qatar)
    "RE": "fr-RE",      # French (Réunion)
    "RO": "ro-RO",      # Romanian (Romania)
    "RU": "ru-RU",      # Russian (Russia)
    "RW": "rw-RW",      # Kinyarwanda (Rwanda)
    "BL": "fr-BL",      # French (Saint Barthélemy)
    "SH": "en-SH",      # English (Saint Helena)
    "KN": "en-KN",      # English (Saint Kitts and Nevis)
    "LC": "en-LC",      # English (Saint Lucia)
    "MF": "fr-MF",      # French (Saint Martin)
    "PM": "fr-PM",      # French (Saint Pierre and Miquelon)
    "VC": "en-VC",      # English (Saint Vincent and the Grenadines)
    "WS": "en-WS",      # English (Samoa)
    "SM": "it-SM",      # Italian (San Marino)
    "ST": "pt-ST",      # Portuguese (São Tomé and Príncipe)
    "SA": "ar-SA",      # Arabic (Saudi Arabia)
    "SN": "fr-SN",      # French (Senegal)
    "RS": "sr-RS",      # Serbian (Serbia)
    "SC": "en-SC",      # English (Seychelles)
    "SL": "en-SL",      # English (Sierra Leone)
    "SG": "en-SG",      # English (Singapore)
    "SK": "sk-SK",      # Slovak (Slovakia)
    "SI": "sl-SI",      # Slovenian (Slovenia)
    "SB": "en-SB",      # English (Solomon Islands)
    "SO": "so-SO",      # Somali (Somalia)
    "ZA": "en-ZA",      # English (South Africa)
    "GS": "en-GS",      # English (South Georgia and the South Sandwich Islands)
    "ES": "es-ES",      # Spanish (Spain)
    "LK": "si-LK",      # Sinhala (Sri Lanka)
    "SD": "ar-SD",      # Arabic (Sudan)
    "SR": "nl-SR",      # Dutch (Suriname)
    "SJ": "no-SJ",      # Norwegian (Svalbard and Jan Mayen)
    "SZ": "en-SZ",      # English (Eswatini)
    "SE": "sv-SE",      # Swedish (Sweden)
    "CH": "de-CH",      # German (Switzerland)
    "SY": "ar-SY",      # Arabic (Syria)
    "TW": "zh-TW",      # Chinese (Taiwan)
    "TJ": "tg-TJ",      # Tajik (Tajikistan)
    "TZ": "en-TZ",      # English (Tanzania)
    "TH": "th-TH",      # Thai (Thailand)
    "TL": "pt-TL",      # Portuguese (Timor-Leste)
    "TG": "fr-TG",      # French (Togo)
    "TK": "en-TK",      # English (Tokelau)
    "TO": "en-TO",      # English (Tonga)
    "TT": "en-TT",      # English (Trinidad and Tobago)
    "TN": "ar-TN",      # Arabic (Tunisia)
    "TR": "tr-TR",      # Turkish (Turkey)
    "TM": "tk-TM",      # Turkmen (Turkmenistan)
    "TV": "en-TV",      # English (Tuvalu)
    "UG": "en-UG",      # English (Uganda)
    "UA": "uk-UA",      # Ukrainian (Ukraine)
    "GB": "en-GB",      # English (United Kingdom)
    "US": "en-US",      # English (United States)
    "UY": "es-UY",      # Spanish (Uruguay)
    "UZ": "uz-UZ",      # Uzbek (Uzbekistan)
    "VU": "en-VU",      # English (Vanuatu)
    "VA": "it-VA",      # Italian (Vatican City)
    "VE": "es-VE",      # Spanish (Venezuela)
    "VN": "vi-VN",      # Vietnamese (Vietnam)
    "VG": "en-VG",      # English (British Virgin Islands)
    "VI": "en-VI",      # English (US Virgin Islands)
    "WF": "fr-WF",      # French (Wallis and Futuna)
    "EH": "ar-EH",      # Arabic (Western Sahara)
    "YE": "ar-YE",      # Arabic (Yemen)
    "ZM": "en-ZM",      # English (Zambia)
    "ZW": "en-ZW",      # English (Zimbabwe)
}